[colors]
ansi = [
    "#1a110f",
    "#ffb4ab",
    "#dbc58c",
    "#e7bdb4",
    "#ffb4a3",
    "#dbc58c",
    "#e7bdb4",
    "#f1dfdb",
]
background = "#1a110f"
brights = [
    "#a08c88",
    "#ffb4ab",
    "#dbc58c",
    "#e7bdb4",
    "#ffb4a3",
    "#dbc58c",
    "#e7bdb4",
    "#f1dfdb",
]
cursor_bg = "#f1dfdb"
cursor_border = "#f1dfdb"
cursor_fg = "#1a110f"
foreground = "#f1dfdb"
selection_bg = "#534340"
selection_fg = "#d8c2bd"

[metadata]
name = "Noctalia"
