[colors]
ansi = ["#000000","#685742","#5f875f","#b36d43","#78824b","#bb7744","#c9a554","#d7c483"]
background = "#222222"
brights = ["#666666","#8a6f5c","#7aa37a","#d08f5f","#95a064","#d89a66","#e0c080","#f0e0b0"]
cursor_bg = "#c7c7c7"
cursor_border = "#c7c7c7"
cursor_fg = "#eeeeee"
foreground = "#c2c2b0"
selection_bg = "#e5c47b"
selection_fg = "#000000"

[metadata]
name = "Miasma (Dark)"
