[colors]
ansi = ["#555550","#a08070","#8fb38f","#d0b090","#a8b87a","#d8a088","#e0d0a0","#333330"]
background = "#fafaf5"
brights = ["#999980","#b89888","#a0c8a0","#e5c8a8","#b8d098","#eab8a0","#f0e0c0","#111110"]
cursor_bg = "#c2c2b0"
cursor_border = "#c2c2b0"
cursor_fg = "#222222"
foreground = "#222222"
selection_bg = "#e5c47b"
selection_fg = "#222222"

[metadata]
name = "Miasma (Light)"
